blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
    path('', views.home, name='home'),
    path('details/<int:id>', views.post_detail, name='details'),
    path('create', views.post_create_view, name='create'),
    path('update/<int:id>', views.post_update_view, name='update'),
    path('delete/<int:id>', views.post_delete_view, name='delete'),
]

mwangi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register', user_views.register, name='register'),
    path('profile', user_views.profile, name='profile'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64> / <token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse()

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

users/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.utils import timezone
from .forms import PostCreateForm, PostUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Post



def home(request):
    posts = Post.objects.all().order_by('-date_posted')
    context = {'posts':posts}
    return render(request, 'blog/home.html', context)


def post_detail(request, id):
    the_post = get_object_or_404(Post, id=id)
    context = { 'the_post':the_post}
    return render(request, 'blog/detail.html', context)



@login_required
def post_create_view(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST or None)
        if form.is_valid():
            the_data = form.save(commit=False)
            the_data.date_posted= timezone.now()
            the_data.author = request.user
            the_data.save()
            return redirect('blog:home')
    else:
        form = PostCreateForm()
    context = {
        'form':form
    }
    return render(request, 'blog/create.html', context)



@login_required
def post_update_view(request, id):
    the_post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostUpdateForm(request.POST or None, instance=the_post)
        if form.is_valid():
            the_update = form.save(commit=False)
            the_update.date_posted = timezone.now()
            the_update.author = request.user
            the_update.save()
            return redirect('blog:home')
    else:
        form = PostUpdateForm(instance=the_post)
    context = { 'form': form }
    return render(request, 'blog/update.html', context)



@login_required
def post_delete_view(request, id):
    the_post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        the_post.delete()
        return redirect('blog:home')
    context = {'the_post': the_post}
    return render(request, 'blog/delete.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created! You are now able to login.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
	{% if title %}
		<title>Django Blog - {{ title }}</title>
	{% else %}
		<title>Django Blog</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="{% url 'blog:home' %}" style="color:black;">Django Blog</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link" href="{% url 'blog:home' %}" style="color:black;">Home</a>
					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if user.is_authenticated %}
							<a class="nav-item nav-link" href="{% url 'blog:create' %}" style="color:black;">New Post</a>
							<a class="nav-item nav-link" href="{% url 'profile' %}" style="color:black;">Profile</a>
							<a class="nav-item nav-link" href="{% url 'logout' %}" style="color:black;">Logout</a>
						{% else %}
							<a class="nav-item nav-link" href="{% url 'login' %}" style="color:black;">Login</a>
							<a class="nav-item nav-link" href="{% url 'register' %}" style="color:black;">Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>
  <br><br>
	<main role="main" class="container">
		<div class="row">
			<div class="col-md-8">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{ message.tags }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
				{% block content %}{% endblock %}
			</div>
			<div class="col-md-4">
				<div class="content-section">
					<h3>Our Sidebar</h3>
					<p class="text-muted">You can put any information here you'd like.
						<ul class="list-group">
							<li class="list-group-item list-group-item-light">Latest Posts</li>
							<li class="list-group-item list-group-item-light">Announcements</li>
							<li class="list-group-item list-group-item-light">Calendars</li>
							<li class="list-group-item list-group-item-light">etc</li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</main>


	 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/create.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
      <br>
      <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>

{% endblock %}

blog/templates/blog/delete.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
      <br>
    <p>Are you sure you want to delete {{the_post.title}} post?</p>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-danger" value="Delete">&nbsp;&nbsp;<a href="{% url 'blog:home' %}">Cancel</a>
    </form>
  </div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
      <br>
    {% if the_post.author == request.user %}
    <div class="btn-group" role="group">
      <a href="{% url 'blog:update' the_post.id %}"><button type="button" class="btn btn-primary">Update Post</button></a>
      <a href="{% url 'blog:delete' the_post.id %}"><button type="button" class="btn btn-warning">Delete It</button></a>
    </div>
    {% endif %}
    <br><br>
    <p>Title: {{the_post.title}} <i>by {{the_post.author}}</i></p>

    <br>
    <p>Content: <br>{{the_post.content}}</p>
  </div>

{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<br>
    <h3>HERE ARE ALL THE POSTS THAT YOU HAVE CREATED</h3>
    <br>
    {% for post in posts %}
    <p>{{forloop.counter}}. <a href="{% url 'blog:details' post.id %}">{{post.title}}</a> by {{post.author}}</p>
    {% endfor %}

{% endblock content %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
      <br>
    <form method="post">
      {% csrf_token %}
      {{form | crispy}}
      <input type="submit" class="btn btn-success" value="Update">
    </form>
  </div>
{% endblock %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Login</button>
				<small class="text-muted" ml-2>
					<a href="{% url 'password_reset' %}">Forgot password?</a>
				</small>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a></small>
		</div>
	</div>
{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
	<div class="border-top pt-3">
		<small class="text-muted">
			<a href="{% url 'login' %}">Log In Again</a>
		</small>
	</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Request Password Reset</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}
	<div class="alert alert-info">
		Your password has been set.
	</div>
	<a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Reset Password</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Reset Password</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
	<div class="alert alert-info">
		An email has been sent with instructions to reset your password
	</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
			<div class="media-body">
				<h2 class="account-heading">{{ user.username }}</h2>
				<p class="text-secondary">{{ user.email }}</p>
			</div>
		</div>
		<!-- Form Here-->
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Profile Info</legend>
				{{ u_form|crispy }}
				{{ p_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Update</button>
			</div>
		</form>
	</div>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign Up</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a></small>
		</div>
	</div>
{% endblock content %}